name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * MON'

jobs:
  test:
    name: PHP ${{ matrix.php-version }} + ${{ matrix.dependencies }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        php-version:
          - '8.1'
          - '8.2'
        dependencies:
          - highest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: intl
          coverage: pcov
          tools: composer:v2, phpunit

      - name: Install Composer dependencies (${{ matrix.dependencies }})
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
          composer-options: --prefer-dist --prefer-stable

      - name: Run tests with coverage
        run: phpunit -c phpunit.xml --coverage-clover tmp/clover.xml

      - name: Send coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: tmp/clover.xml
